trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Jacked@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'directory'
    scanName: 'dev-jacked-azure'
    failCriteria: 'medium'
    skipBuildFail: 'false'